# swagger 
openapi: 3.0.0
info:
  title: "URL Shortener"
  description: "Create shorter URLs"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Url:
      type: "object"
      required:
        - url
      properties:
        shortcode:
          type: "string" 
        url: 
          type: "string"
  parameters:
    shortcode:
      name: "shortcode"
      description: "Read short code information"
      in: path
      required: true
      schema:
        type: "string"
        
paths:
  /shorten:
    post:
      operationId: "shortcode.create"
      tags:
        - Shorten
      summary: "Create short code for URLs"
      requestBody:
        description: "Create new short code for URL"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "url"
              $ref: "#/components/schemas/Url"
      responses:
        "201":
          description: "Successfully create new short code"
  /{shortcode}:
    get:
      operationId: "shortcode.read"
      tags:
        - "Shorten"
      summary: "Read Short code information"
      parameters:
        - $ref: "#/components/parameters/shortcode"
      responses:
        "200":
          description: "Successfully read Short code"
  /{shortcode}/stats:
    get:
      operationId: "shortcode.get_stats"
      tags:
        - "Shorten"
      summary: "Read Short code information"
      parameters:
        - $ref: "#/components/parameters/shortcode"
      responses:
        "200":
          description: "Successfully read Short code"
